#!/usr/bin/env python3
"""Configure repository-specific publication metadata safely and deterministically."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from urllib.parse import urlparse

REPOSITORY_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")
CODEOWNER_RE = re.compile(r"^@[A-Za-z0-9-]+$")


def read_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_manifest_json(path: Path, value: dict[str, object]) -> None:
    """Write a Home Assistant manifest in hassfest's required key order."""
    ordered: dict[str, object] = {
        "domain": value["domain"],
        "name": value["name"],
    }
    ordered.update(
        (key, value[key])
        for key in sorted(value)
        if key not in {"domain", "name"}
    )
    path.write_text(json.dumps(ordered, indent=2) + "\n", encoding="utf-8")


def configure(root: Path, repository: str, codeowners: list[str]) -> None:
    if not REPOSITORY_RE.fullmatch(repository):
        raise SystemExit("Repository must use the GitHub OWNER/REPOSITORY form")
    normalized: list[str] = []
    for owner in codeowners:
        candidate = owner if owner.startswith("@") else f"@{owner}"
        if not CODEOWNER_RE.fullmatch(candidate):
            raise SystemExit(f"Invalid GitHub code owner: {owner}")
        if candidate not in normalized:
            normalized.append(candidate)
    if not normalized:
        raise SystemExit("At least one GitHub code owner is required")

    repository_url = f"https://github.com/{repository}"
    parsed = urlparse(repository_url)
    if parsed.scheme != "https" or parsed.netloc != "github.com":
        raise SystemExit("Publication repository must be hosted on GitHub over HTTPS")

    manifest_path = root / "custom_components/portfolio_architect/manifest.json"
    manifest = read_json(manifest_path)
    manifest["documentation"] = f"{repository_url}#readme"
    manifest["issue_tracker"] = f"{repository_url}/issues"
    manifest["codeowners"] = normalized
    write_manifest_json(manifest_path, manifest)

    publication = {
        "schema": 1,
        "configured": True,
        "github_repository": repository,
        "codeowners": normalized,
    }
    write_json(root / "publication.json", publication)

    owners = " ".join(normalized)
    codeowners_text = (
        "# Generated by tools/configure_publication.py.\n"
        f"* {owners}\n"
        f"/.github/workflows/ {owners}\n"
        f"/.github/dependabot.yml {owners}\n"
        f"/tools/configure_publication.py {owners}\n"
        f"/tools/check_publication.py {owners}\n"
        f"/tools/check_privacy.py {owners}\n"
        f"/tools/run_gitleaks_ci.sh {owners}\n"
        f"/tools/release_check.sh {owners}\n"
        f"/custom_components/portfolio_architect/ {owners}\n"
        f"/home_assistant_app/portfolio_architect_gateway_comdirect/ {owners}\n"
        f"/home_assistant_app/portfolio_architect_gateway_dkb/ {owners}\n"
        f"/home_assistant_app/portfolio_architect_gateway_trade_republic/ {owners}\n"
        f"/home_assistant_app/portfolio_architect_gateway_import/ {owners}\n"
        f"/gateway/ {owners}\n"
    )
    (root / ".github/CODEOWNERS").write_text(codeowners_text, encoding="utf-8")
    (root / ".github/CODEOWNERS.example").unlink(missing_ok=True)

    # These files describe the immutable downloaded source archive. They become
    # stale as soon as repository-specific metadata is written and therefore
    # must not be committed as mutable repository content. Release builds create
    # fresh copies inside every complete-source archive.
    (root / "PACKAGE-MANIFEST.json").unlink(missing_ok=True)
    (root / "SHA256SUMS").unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--repository", required=True, help="GitHub OWNER/REPOSITORY")
    parser.add_argument("--codeowner", action="append", required=True)
    args = parser.parse_args()
    configure(args.root.resolve(), args.repository, args.codeowner)
    print(f"Configured publication metadata for {args.repository}")


if __name__ == "__main__":
    main()
